[project]
name = "review_bot"
description = "A simple but using local llms to review code"
version = "0.1"
readme = "Readme.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  {name = "David Gunzinger", email = "david.gunzinger@smoca.ch"},
  {name = "Martin Defuns", email = "martin.defuns@smoca.ch"}
]
dependencies = [
    "python-dotenv",
    "requests",
    "openai",
    "beautifulsoup4",
    "pydantic_ai",
    "pydantic-ai-slim[anthropic]",
    "pydantic-ai-slim[web-fetch]",
    "opentelemetry-sdk"
]


[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
review-bot = "review_bot:main"
review-bot-gitlab-webhook = "review_bot.gitlab_webhook:main"
